#!/usr/bin/env python3
"""Generates the DEV-ONLY realm exports in ./realms (kept so the two JSON
files stay consistent). Run: python3 keycloak/gen_realms.py

Sign-in paths (asserted by KeycloakRealmExportIT):
  staff   - a passkey (user verification required) OR password + TOTP.
            No password-only path, including direct grants and password reset.
  citizen - email one-time code (samanvay-email-otp, keycloak/email-otp) OR a
            passkey. No passwords, no TOTP; direct grants are denied.

Nothing here is a real secret: staff dev users have *temporary* passwords that
must be changed (and TOTP enrolled) on first login; the citizen dev user has no
password at all; the department client's secret is generated by Keycloak at
import and never committed. Mail goes to the dev/test Mailpit container.
"""
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))
UI_ORIGIN = "http://localhost:8080"
# Data sources the dev department client may fetch from: one scope per source.
DEPT_SOURCES = ["revenue-rest-mock", "education-soap-mock", "dbt-rest-mock"]
# Every token the API accepts must name it in `aud` (checked by the resource
# server together with an azp allow-list, see SecurityConfig). Only the clients
# below get this mapper, so admin-cli/account-console tokens never qualify.
API_AUDIENCE = "samanvay-api"


def mapper(name, kind, **config):
    return {"name": name, "protocol": "openid-connect", "protocolMapper": kind,
            "consentRequired": False, "config": {k.replace("_", "."): v for k, v in config.items()}}


def api_audience_mapper():
    return mapper("samanvay-api audience", "oidc-audience-mapper", included_custom_audience=API_AUDIENCE,
                  access_token_claim="true", id_token_claim="false", introspection_token_claim="true")


# The catalog department an officer belongs to (e.g. SCHOLARSHIP) is an
# admin-managed user attribute, released as the `department` access-token
# claim; users cannot edit it (user profile below). Department clients get the
# same claim hardcoded on the client. The API binds consent requests to it.
DEPT_CLIENT_DEPARTMENT = "SCHOLARSHIP"


def department_attribute_mapper():
    return mapper("department", "oidc-usermodel-attribute-mapper", user_attribute="department",
                  claim_name="department", jsonType_label="String", access_token_claim="true",
                  id_token_claim="false", introspection_token_claim="true", userinfo_token_claim="false")


def department_hardcoded_mapper(code):
    return mapper("department", "oidc-hardcoded-claim-mapper", claim_name="department", claim_value=code,
                  jsonType_label="String", access_token_claim="true", id_token_claim="false",
                  introspection_token_claim="true", userinfo_token_claim="false")


def _up_attr(name, display, validations, required=False, admin_only=False):
    a = {"name": name, "displayName": display, "validations": validations, "multivalued": False,
         "permissions": {"view": ["admin"] if admin_only else ["admin", "user"],
                         "edit": ["admin"] if admin_only else ["admin", "user"]}}
    if required:
        a["required"] = {"roles": ["user"]}
    return a


def user_profile(extra_attributes=()):
    """Declarative user profile (Keycloak 24+). Unmanaged attributes stay admin-only."""
    config = {
        "attributes": [
            _up_attr("username", "${username}", {"length": {"min": 3, "max": 255},
                                                 "username-prohibited-characters": {},
                                                 "up-username-not-idn-homograph": {}}),
            _up_attr("email", "${email}", {"email": {}, "length": {"max": 255}}, required=True),
            _up_attr("firstName", "${firstName}", {"length": {"max": 255}, "person-name-prohibited-characters": {}},
                     required=True),
            _up_attr("lastName", "${lastName}", {"length": {"max": 255}, "person-name-prohibited-characters": {}},
                     required=True),
            *extra_attributes,
        ],
        "groups": [{"name": "user-metadata", "displayHeader": "User metadata",
                    "displayDescription": "Attributes, which refer to user metadata"}],
        "unmanagedAttributePolicy": "ADMIN_EDIT",
    }
    return {"org.keycloak.userprofile.UserProfileProvider": [{
        "providerId": "declarative-user-profile", "subComponents": {},
        "config": {"kc.user.profile.config": [json.dumps(config, separators=(",", ":"))]}}]}


def scope(name, description, mappers=(), in_token_scope=True):
    return {"name": name, "description": description, "protocol": "openid-connect",
            "attributes": {"include.in.token.scope": str(in_token_scope).lower(),
                           "display.on.consent.screen": "false"},
            "protocolMappers": list(mappers)}


BASE_SCOPES = [
    scope("basic", "sub + auth_time", [
        mapper("sub", "oidc-sub-mapper", access_token_claim="true", introspection_token_claim="true"),
        mapper("auth_time", "oidc-usersessionmodel-note-mapper", user_session_note="AUTH_TIME",
               claim_name="auth_time", jsonType_label="long", id_token_claim="true",
               access_token_claim="true", introspection_token_claim="true"),
    ], in_token_scope=False),
    scope("roles", "realm roles as realm_access.roles", [
        mapper("realm roles", "oidc-usermodel-realm-role-mapper", claim_name="realm_access.roles",
               multivalued="true", jsonType_label="String", access_token_claim="true",
               id_token_claim="false", introspection_token_claim="true", userinfo_token_claim="false"),
    ], in_token_scope=False),
    scope("profile", "preferred_username", [
        mapper("username", "oidc-usermodel-property-mapper", user_attribute="username",
               claim_name="preferred_username", jsonType_label="String", access_token_claim="true",
               id_token_claim="true", introspection_token_claim="true", userinfo_token_claim="true"),
    ]),
    scope("web-origins", "allowed CORS origins", [
        mapper("allowed web origins", "oidc-allowed-origins-mapper", access_token_claim="true",
               introspection_token_claim="true"),
    ], in_token_scope=False),
    scope("acr", "acr loa level", [
        mapper("acr loa level", "oidc-acr-mapper", id_token_claim="true", access_token_claim="true",
               introspection_token_claim="true"),
    ], in_token_scope=False),
]

WEBAUTHN_PASSKEYS = {
    # Passkeys (WebAuthn passwordless) allowed as a sign-in method.
    "webAuthnPolicyPasswordlessRpEntityName": None,  # filled per realm
    "webAuthnPolicyPasswordlessSignatureAlgorithms": ["ES256", "RS256"],
    "webAuthnPolicyPasswordlessAttestationConveyancePreference": "not specified",
    "webAuthnPolicyPasswordlessAuthenticatorAttachment": "not specified",
    "webAuthnPolicyPasswordlessRequireResidentKey": "Yes",
    "webAuthnPolicyPasswordlessUserVerificationRequirement": "required",
    "webAuthnPolicyPasswordlessCreateTimeout": 0,
    "webAuthnPolicyPasswordlessAvoidSameAuthenticatorRegister": False,
    "webAuthnPolicyPasswordlessAcceptableAaguids": [],
    "webAuthnPolicyPasswordlessExtraOrigins": [],
    "webAuthnPolicyPasswordlessPasskeysEnabled": True,
}

OTP_POLICY = {
    "otpPolicyType": "totp", "otpPolicyAlgorithm": "HmacSHA1", "otpPolicyDigits": 6,
    "otpPolicyLookAheadWindow": 1, "otpPolicyPeriod": 30, "otpPolicyCodeReusable": False,
}


def execution(authenticator, requirement, priority, flow_alias=None, config=None):
    e = {"requirement": requirement, "priority": priority, "userSetupAllowed": False,
         "autheticatorFlow": flow_alias is not None}
    if authenticator:
        e["authenticator"] = authenticator
    if flow_alias:
        e["flowAlias"] = flow_alias
    if config:
        e["authenticatorConfig"] = config
    return e


def flow(alias, description, executions, top_level=True, provider="basic-flow"):
    return {"alias": alias, "description": description, "providerId": provider,
            "topLevel": top_level, "builtIn": False, "authenticationExecutions": executions}


# "Condition - credential": true when NO passkey was used in this login, so the
# second step (TOTP for staff, email code for citizens) is skipped only for a
# passkey sign-in - which itself required user verification.
NOT_PASSKEY_CONFIG = {"alias": "not signed in with a passkey",
                      "config": {"credentials": "webauthn-passwordless", "included": "false"}}


def required_actions(staff):
    # Citizens never get TOTP or a password: CONFIGURE_TOTP / UPDATE_PASSWORD are off.
    return [
        {"alias": "CONFIGURE_TOTP", "name": "Configure OTP", "providerId": "CONFIGURE_TOTP",
         "enabled": staff, "defaultAction": staff, "priority": 10, "config": {}},
        {"alias": "UPDATE_PASSWORD", "name": "Update Password", "providerId": "UPDATE_PASSWORD",
         "enabled": staff, "defaultAction": False, "priority": 30, "config": {}},
        {"alias": "webauthn-register-passwordless", "name": "Webauthn Register Passwordless",
         "providerId": "webauthn-register-passwordless", "enabled": True, "defaultAction": False,
         "priority": 80, "config": {}},
        {"alias": "VERIFY_EMAIL", "name": "Verify Email", "providerId": "VERIFY_EMAIL",
         "enabled": True, "defaultAction": False, "priority": 50, "config": {}},
    ]


def ui_client(client_id, name, extra_scopes=()):
    return {"clientId": client_id, "name": name, "enabled": True, "publicClient": True,
            "protocol": "openid-connect", "standardFlowEnabled": True, "implicitFlowEnabled": False,
            "directAccessGrantsEnabled": False, "serviceAccountsEnabled": False,
            "redirectUris": [UI_ORIGIN + "/*"], "webOrigins": [UI_ORIGIN],
            "attributes": {"pkce.code.challenge.method": "S256", "post.logout.redirect.uris": UI_ORIGIN + "/*"},
            "defaultClientScopes": ["basic", "roles", "profile", "web-origins", "acr", *extra_scopes],
            "optionalClientScopes": [],
            "protocolMappers": [api_audience_mapper()]}


def dev_user(username, roles, actions, department=None, password=True):
    attributes = {"note": ["DEV-ONLY test user - never import into a real environment"]}
    if department:
        attributes["department"] = [department]
    return {"username": username, "enabled": True, "emailVerified": True,
            "email": username + "@dev.samanvay.invalid", "firstName": "DEV", "lastName": username,
            "attributes": attributes,
            "credentials": [{"type": "password", "value": username + "-change-me", "temporary": True}] if password else [],
            "requiredActions": actions, "realmRoles": roles}


def staff_realm():
    realm = "samanvay-staff"
    source_scopes = [scope("source:" + s, "Department client may fetch from data source " + s) for s in DEPT_SOURCES]
    service_account_scope = scope("service_account", "client_id claim on client-credentials tokens", [
        mapper("client id", "oidc-usersessionmodel-note-mapper", user_session_note="client_id",
               claim_name="client_id", jsonType_label="String", id_token_claim="false",
               access_token_claim="true", introspection_token_claim="true"),
    ], in_token_scope=False)
    department_scope = scope("department", "catalog department of the staff member (admin-managed attribute)",
                             [department_attribute_mapper()], in_token_scope=False)
    rep = {
        "realm": realm, "displayName": "Samanvay staff (DEV)", "enabled": True,
        "sslRequired": "external", "registrationAllowed": False, "resetPasswordAllowed": False,
        "loginWithEmailAllowed": False, "bruteForceProtected": True, "accessTokenLifespan": 300,
        **OTP_POLICY,
        **{**WEBAUTHN_PASSKEYS, "webAuthnPolicyPasswordlessRpEntityName": "Samanvay staff"},
        "roles": {"realm": [
            {"name": "officer", "description": "Department officer: exception queue, retries"},
            {"name": "reviewer", "description": "Identity reviewer: confirm/reject candidate links"},
            {"name": "admin", "description": "Integration admin: catalog and onboarding writes"},
            {"name": "department", "description": "Department integration - client-credentials service accounts ONLY"},
            {"name": "default-roles-" + realm, "composite": True, "composites": {"realm": []}},
        ]},
        "defaultRole": {"name": "default-roles-" + realm, "composite": True},
        "components": user_profile([_up_attr("department", "Department", {"length": {"max": 60}}, admin_only=True)]),
        "clientScopes": BASE_SCOPES + [service_account_scope, department_scope] + source_scopes,
        "defaultDefaultClientScopes": ["basic", "roles", "profile", "web-origins", "acr"],
        "defaultOptionalClientScopes": [],
        "clients": [
            ui_client("samanvay-staff-ui", "Samanvay staff consoles (dev)", extra_scopes=["department"]),
            {"clientId": "dept-scholarship-dev", "name": "DEV department client (scholarship sources)",
             "enabled": True, "publicClient": False, "clientAuthenticatorType": "client-secret",
             "protocol": "openid-connect", "standardFlowEnabled": False, "implicitFlowEnabled": False,
             "directAccessGrantsEnabled": False, "serviceAccountsEnabled": True,
             "attributes": {"access.token.lifespan": "300"},
             # secret intentionally absent: Keycloak generates one at import.
             "defaultClientScopes": ["basic", "roles", "service_account"] + ["source:" + s for s in DEPT_SOURCES],
             "optionalClientScopes": [],
             "protocolMappers": [api_audience_mapper(), department_hardcoded_mapper(DEPT_CLIENT_DEPARTMENT)]},
        ],
        "users": [
            dev_user("dev-officer", ["officer"], ["CONFIGURE_TOTP", "UPDATE_PASSWORD"], department="SCHOLARSHIP"),
            dev_user("dev-reviewer", ["reviewer"], ["CONFIGURE_TOTP", "UPDATE_PASSWORD"]),
            dev_user("dev-admin", ["admin"], ["CONFIGURE_TOTP", "UPDATE_PASSWORD"]),
            {"username": "service-account-dept-scholarship-dev", "enabled": True,
             "serviceAccountClientId": "dept-scholarship-dev", "realmRoles": ["department"]},
        ],
        # Staff: a passkey (user verification required, see WEBAUTHN_PASSKEYS),
        # OR password + TOTP. The passkey is offered on the username/password
        # form; TOTP is REQUIRED unless that passkey was used - never optional,
        # never "only if configured" (a staff member without TOTP must enrol it
        # right after the password). No password-only path anywhere.
        "authenticationFlows": [
            flow("staff browser", "Passkey, or password + TOTP", [
                execution("auth-cookie", "ALTERNATIVE", 10),
                execution(None, "ALTERNATIVE", 20, flow_alias="staff browser forms"),
            ]),
            flow("staff browser forms", "username/password (or passkey), then TOTP unless passkey", [
                execution("auth-username-password-form", "REQUIRED", 10),
                execution(None, "CONDITIONAL", 20, flow_alias="staff second factor"),
            ], top_level=False),
            flow("staff second factor", "TOTP for every non-passkey sign-in", [
                execution("conditional-credential", "REQUIRED", 10, config=NOT_PASSKEY_CONFIG["alias"]),
                execution("auth-otp-form", "REQUIRED", 20),
            ], top_level=False),
            flow("staff direct grant", "Direct grant also demands TOTP", [
                execution("direct-grant-validate-username", "REQUIRED", 10),
                execution("direct-grant-validate-password", "REQUIRED", 20),
                execution("direct-grant-validate-otp", "REQUIRED", 30),
            ]),
            # Self-service reset is off (resetPasswordAllowed=false: admins reset,
            # issuing a temporary password that then goes through the browser
            # flow above). If it is ever turned on, it still demands the TOTP
            # before a new password is set - and never resets the TOTP.
            flow("staff reset credentials", "Reset password only after TOTP", [
                execution("reset-credentials-choose-user", "REQUIRED", 10),
                execution("reset-credential-email", "REQUIRED", 20),
                execution("auth-otp-form", "REQUIRED", 30),
                execution("reset-password", "REQUIRED", 40),
            ]),
        ],
        "authenticatorConfig": [NOT_PASSKEY_CONFIG],
        "browserFlow": "staff browser",
        "directGrantFlow": "staff direct grant",
        "resetCredentialsFlow": "staff reset credentials",
        "requiredActions": required_actions(staff=True),
    }
    return rep


def citizen_realm():
    realm = "samanvay-citizen"
    return {
        "realm": realm, "displayName": "Samanvay citizen sign-in (DEV)", "enabled": True,
        "sslRequired": "external", "registrationAllowed": True, "registrationEmailAsUsername": False,
        "verifyEmail": True, "loginWithEmailAllowed": True, "bruteForceProtected": True,
        "resetPasswordAllowed": False, "accessTokenLifespan": 300,
        # DEV/test mail catcher (docker compose + ITs: Mailpit at mailpit:1025).
        "smtpServer": {"host": "mailpit", "port": "1025", "from": "no-reply@dev.samanvay.invalid",
                       "fromDisplayName": "Samanvay citizen services (DEV)", "auth": "false",
                       "ssl": "false", "starttls": "false"},
        **OTP_POLICY,
        **{**WEBAUTHN_PASSKEYS, "webAuthnPolicyPasswordlessRpEntityName": "Samanvay citizen services"},
        "roles": {"realm": [
            {"name": "citizen", "description": "Citizen acting on their own records"},
            {"name": "default-roles-" + realm, "composite": True, "composites": {"realm": ["citizen"]}},
        ]},
        "defaultRole": {"name": "default-roles-" + realm, "composite": True},
        "clientScopes": BASE_SCOPES,
        "defaultDefaultClientScopes": ["basic", "roles", "profile", "web-origins", "acr"],
        "defaultOptionalClientScopes": [],
        "clients": [
            ui_client("samanvay-citizen-ui", "Samanvay citizen portals (dev)"),
            # Built-in client, redefined so its password grant is off in this realm.
            {"clientId": "admin-cli", "name": "${client_admin-cli}", "enabled": True, "publicClient": True,
             "protocol": "openid-connect", "standardFlowEnabled": False, "implicitFlowEnabled": False,
             "directAccessGrantsEnabled": False, "serviceAccountsEnabled": False},
        ],
        "users": [
            # No password, no required actions: signs in with an emailed code
            # (read it in Mailpit, http://localhost:8025).
            dev_user("dev-citizen", ["citizen"], [], password=False),
        ],
        # Citizen: email one-time code first (a mailbox the citizen already
        # holds), or a passkey. Passkeys are registered only after an email-code
        # sign-in. No passwords and no TOTP anywhere in this realm.
        "authenticationFlows": [
            flow("citizen browser", "Email one-time code, or passkey", [
                execution("auth-cookie", "ALTERNATIVE", 10),
                execution(None, "ALTERNATIVE", 20, flow_alias="citizen browser forms"),
            ]),
            flow("citizen browser forms", "username/email (or passkey), then email code unless passkey", [
                execution("auth-username-form", "REQUIRED", 10),
                execution(None, "CONDITIONAL", 20, flow_alias="citizen email code"),
            ], top_level=False),
            flow("citizen email code", "Email one-time code for every non-passkey sign-in", [
                execution("conditional-credential", "REQUIRED", 10, config=NOT_PASSKEY_CONFIG["alias"]),
                execution("samanvay-email-otp", "REQUIRED", 20, config="email code settings"),
            ], top_level=False),
            # Direct grants (password grant) are denied for every client.
            flow("citizen direct grant disabled", "Citizens never sign in with a password grant", [
                execution("deny-access-authenticator", "REQUIRED", 10),
            ]),
            # Self-registration asks for profile data only - no password. The
            # new account's email is then verified by link (verifyEmail) before
            # the first token, and later sign-ins use the email code.
            flow("citizen registration", "Registration without a password", [
                execution("registration-page-form", "REQUIRED", 10, flow_alias="citizen registration form"),
            ]),
            flow("citizen registration form", "Profile only", [
                execution("registration-user-creation", "REQUIRED", 20),
                execution("registration-recaptcha-action", "DISABLED", 60),
                execution("registration-terms-and-conditions", "DISABLED", 70),
            ], top_level=False, provider="form-flow"),
        ],
        "authenticatorConfig": [
            NOT_PASSKEY_CONFIG,
            {"alias": "email code settings", "config": {"length": "6", "ttlSeconds": "300", "maxAttempts": "5"}},
        ],
        "browserFlow": "citizen browser",
        "directGrantFlow": "citizen direct grant disabled",
        "registrationFlow": "citizen registration",
        "requiredActions": required_actions(staff=False),
    }


for rep in (staff_realm(), citizen_realm()):
    path = os.path.join(HERE, "realms", rep["realm"] + "-realm.json")
    with open(path, "w") as f:
        json.dump(rep, f, indent=2, ensure_ascii=False)
        f.write("\n")
    print("wrote", path)
