#!/usr/bin/env python3
"""Generates the DEV-ONLY realm exports in ./realms (kept so the two JSON
files stay consistent). Run: python3 keycloak/gen_realms.py

Nothing here is a real secret: dev users have *temporary* passwords that must
be changed (and TOTP enrolled, for staff) on first login; the department
client's secret is generated by Keycloak at import and never committed.
"""
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))
UI_ORIGIN = "http://localhost:8080"
# Data sources the dev department client may fetch from: one scope per source.
DEPT_SOURCES = ["revenue-rest-mock", "education-soap-mock", "dbt-rest-mock"]


def mapper(name, kind, **config):
    return {"name": name, "protocol": "openid-connect", "protocolMapper": kind,
            "consentRequired": False, "config": {k.replace("_", "."): v for k, v in config.items()}}


def scope(name, description, mappers=(), in_token_scope=True):
    return {"name": name, "description": description, "protocol": "openid-connect",
            "attributes": {"include.in.token.scope": str(in_token_scope).lower(),
                           "display.on.consent.screen": "false"},
            "protocolMappers": list(mappers)}


BASE_SCOPES = [
    scope("basic", "sub + auth_time", [
        mapper("sub", "oidc-sub-mapper", access_token_claim="true", introspection_token_claim="true"),
        mapper("auth_time", "oidc-usersessionmodel-note-mapper", user_session_note="AUTH_TIME",
               claim_name="auth_time", jsonType_label="long", id_token_claim="true",
               access_token_claim="true", introspection_token_claim="true"),
    ], in_token_scope=False),
    scope("roles", "realm roles as realm_access.roles", [
        mapper("realm roles", "oidc-usermodel-realm-role-mapper", claim_name="realm_access.roles",
               multivalued="true", jsonType_label="String", access_token_claim="true",
               id_token_claim="false", introspection_token_claim="true", userinfo_token_claim="false"),
    ], in_token_scope=False),
    scope("profile", "preferred_username", [
        mapper("username", "oidc-usermodel-property-mapper", user_attribute="username",
               claim_name="preferred_username", jsonType_label="String", access_token_claim="true",
               id_token_claim="true", introspection_token_claim="true", userinfo_token_claim="true"),
    ]),
    scope("web-origins", "allowed CORS origins", [
        mapper("allowed web origins", "oidc-allowed-origins-mapper", access_token_claim="true",
               introspection_token_claim="true"),
    ], in_token_scope=False),
    scope("acr", "acr loa level", [
        mapper("acr loa level", "oidc-acr-mapper", id_token_claim="true", access_token_claim="true",
               introspection_token_claim="true"),
    ], in_token_scope=False),
]

WEBAUTHN_PASSKEYS = {
    # Passkeys (WebAuthn passwordless) allowed as a sign-in method.
    "webAuthnPolicyPasswordlessRpEntityName": None,  # filled per realm
    "webAuthnPolicyPasswordlessSignatureAlgorithms": ["ES256", "RS256"],
    "webAuthnPolicyPasswordlessAttestationConveyancePreference": "not specified",
    "webAuthnPolicyPasswordlessAuthenticatorAttachment": "not specified",
    "webAuthnPolicyPasswordlessRequireResidentKey": "Yes",
    "webAuthnPolicyPasswordlessUserVerificationRequirement": "required",
    "webAuthnPolicyPasswordlessCreateTimeout": 0,
    "webAuthnPolicyPasswordlessAvoidSameAuthenticatorRegister": False,
    "webAuthnPolicyPasswordlessAcceptableAaguids": [],
    "webAuthnPolicyPasswordlessExtraOrigins": [],
    "webAuthnPolicyPasswordlessPasskeysEnabled": True,
}

OTP_POLICY = {
    "otpPolicyType": "totp", "otpPolicyAlgorithm": "HmacSHA1", "otpPolicyDigits": 6,
    "otpPolicyLookAheadWindow": 1, "otpPolicyPeriod": 30, "otpPolicyCodeReusable": False,
}


def execution(authenticator, requirement, priority, flow_alias=None):
    e = {"requirement": requirement, "priority": priority, "userSetupAllowed": False,
         "autheticatorFlow": flow_alias is not None}
    if flow_alias:
        e["flowAlias"] = flow_alias
    else:
        e["authenticator"] = authenticator
    return e


def flow(alias, description, executions, top_level=True):
    return {"alias": alias, "description": description, "providerId": "basic-flow",
            "topLevel": top_level, "builtIn": False, "authenticationExecutions": executions}


def required_actions(default_totp):
    return [
        {"alias": "CONFIGURE_TOTP", "name": "Configure OTP", "providerId": "CONFIGURE_TOTP",
         "enabled": True, "defaultAction": default_totp, "priority": 10, "config": {}},
        {"alias": "UPDATE_PASSWORD", "name": "Update Password", "providerId": "UPDATE_PASSWORD",
         "enabled": True, "defaultAction": False, "priority": 30, "config": {}},
        {"alias": "webauthn-register-passwordless", "name": "Webauthn Register Passwordless",
         "providerId": "webauthn-register-passwordless", "enabled": True, "defaultAction": False,
         "priority": 80, "config": {}},
        {"alias": "VERIFY_EMAIL", "name": "Verify Email", "providerId": "VERIFY_EMAIL",
         "enabled": True, "defaultAction": False, "priority": 50, "config": {}},
    ]


def ui_client(client_id, name):
    return {"clientId": client_id, "name": name, "enabled": True, "publicClient": True,
            "protocol": "openid-connect", "standardFlowEnabled": True, "implicitFlowEnabled": False,
            "directAccessGrantsEnabled": False, "serviceAccountsEnabled": False,
            "redirectUris": [UI_ORIGIN + "/*"], "webOrigins": [UI_ORIGIN],
            "attributes": {"pkce.code.challenge.method": "S256", "post.logout.redirect.uris": UI_ORIGIN + "/*"},
            "defaultClientScopes": ["basic", "roles", "profile", "web-origins", "acr"],
            "optionalClientScopes": []}


def dev_user(username, roles, actions):
    return {"username": username, "enabled": True, "emailVerified": True,
            "email": username + "@dev.samanvay.invalid", "firstName": "DEV", "lastName": username,
            "attributes": {"note": ["DEV-ONLY test user - never import into a real environment"]},
            "credentials": [{"type": "password", "value": username + "-change-me", "temporary": True}],
            "requiredActions": actions, "realmRoles": roles}


def staff_realm():
    realm = "samanvay-staff"
    source_scopes = [scope("source:" + s, "Department client may fetch from data source " + s) for s in DEPT_SOURCES]
    service_account_scope = scope("service_account", "client_id claim on client-credentials tokens", [
        mapper("client id", "oidc-usersessionmodel-note-mapper", user_session_note="client_id",
               claim_name="client_id", jsonType_label="String", id_token_claim="false",
               access_token_claim="true", introspection_token_claim="true"),
    ], in_token_scope=False)
    rep = {
        "realm": realm, "displayName": "Samanvay staff (DEV)", "enabled": True,
        "sslRequired": "external", "registrationAllowed": False, "resetPasswordAllowed": False,
        "loginWithEmailAllowed": False, "bruteForceProtected": True, "accessTokenLifespan": 300,
        **OTP_POLICY,
        **{**WEBAUTHN_PASSKEYS, "webAuthnPolicyPasswordlessRpEntityName": "Samanvay staff"},
        "roles": {"realm": [
            {"name": "officer", "description": "Department officer: exception queue, retries"},
            {"name": "reviewer", "description": "Identity reviewer: confirm/reject candidate links"},
            {"name": "admin", "description": "Integration admin: catalog and onboarding writes"},
            {"name": "department", "description": "Department integration - client-credentials service accounts ONLY"},
            {"name": "default-roles-" + realm, "composite": True, "composites": {"realm": []}},
        ]},
        "defaultRole": {"name": "default-roles-" + realm, "composite": True},
        "clientScopes": BASE_SCOPES + [service_account_scope] + source_scopes,
        "defaultDefaultClientScopes": ["basic", "roles", "profile", "web-origins", "acr"],
        "defaultOptionalClientScopes": [],
        "clients": [
            ui_client("samanvay-staff-ui", "Samanvay staff consoles (dev)"),
            {"clientId": "dept-scholarship-dev", "name": "DEV department client (scholarship sources)",
             "enabled": True, "publicClient": False, "clientAuthenticatorType": "client-secret",
             "protocol": "openid-connect", "standardFlowEnabled": False, "implicitFlowEnabled": False,
             "directAccessGrantsEnabled": False, "serviceAccountsEnabled": True,
             "attributes": {"access.token.lifespan": "300"},
             # secret intentionally absent: Keycloak generates one at import.
             "defaultClientScopes": ["basic", "roles", "service_account"] + ["source:" + s for s in DEPT_SOURCES],
             "optionalClientScopes": []},
        ],
        "users": [
            dev_user("dev-officer", ["officer"], ["CONFIGURE_TOTP", "UPDATE_PASSWORD"]),
            dev_user("dev-reviewer", ["reviewer"], ["CONFIGURE_TOTP", "UPDATE_PASSWORD"]),
            dev_user("dev-admin", ["admin"], ["CONFIGURE_TOTP", "UPDATE_PASSWORD"]),
            {"username": "service-account-dept-scholarship-dev", "enabled": True,
             "serviceAccountClientId": "dept-scholarship-dev", "realmRoles": ["department"]},
        ],
        # Staff: password AND TOTP, both REQUIRED (not conditional). Passkeys are
        # offered on the same username form when a staff member has registered one.
        "authenticationFlows": [
            flow("staff browser", "Password + TOTP required", [
                execution("auth-cookie", "ALTERNATIVE", 10),
                execution(None, "ALTERNATIVE", 20, flow_alias="staff browser forms"),
            ]),
            flow("staff browser forms", "username/password then TOTP", [
                execution("auth-username-password-form", "REQUIRED", 10),
                execution("auth-otp-form", "REQUIRED", 20),
            ], top_level=False),
            flow("staff direct grant", "Direct grant also demands TOTP", [
                execution("direct-grant-validate-username", "REQUIRED", 10),
                execution("direct-grant-validate-password", "REQUIRED", 20),
                execution("direct-grant-validate-otp", "REQUIRED", 30),
            ]),
        ],
        "browserFlow": "staff browser",
        "directGrantFlow": "staff direct grant",
        "requiredActions": required_actions(default_totp=True),
    }
    return rep


def citizen_realm():
    realm = "samanvay-citizen"
    return {
        "realm": realm, "displayName": "Samanvay citizen sign-in (DEV)", "enabled": True,
        "sslRequired": "external", "registrationAllowed": True, "registrationEmailAsUsername": False,
        "verifyEmail": True, "loginWithEmailAllowed": True, "bruteForceProtected": True,
        "accessTokenLifespan": 300,
        **OTP_POLICY,
        **{**WEBAUTHN_PASSKEYS, "webAuthnPolicyPasswordlessRpEntityName": "Samanvay citizen services"},
        "roles": {"realm": [
            {"name": "citizen", "description": "Citizen acting on their own records"},
            {"name": "default-roles-" + realm, "composite": True, "composites": {"realm": ["citizen"]}},
        ]},
        "defaultRole": {"name": "default-roles-" + realm, "composite": True},
        "clientScopes": BASE_SCOPES,
        "defaultDefaultClientScopes": ["basic", "roles", "profile", "web-origins", "acr"],
        "defaultOptionalClientScopes": [],
        "clients": [ui_client("samanvay-citizen-ui", "Samanvay citizen portals (dev)")],
        "users": [
            dev_user("dev-citizen", ["citizen"], ["CONFIGURE_TOTP"]),
        ],
        # Citizen: one-time-code sign-in (username + OTP, no password). The
        # production SMS/Aadhaar OTP provider is out of scope; TOTP stands in for
        # dev. Passkeys are an allowed alternative on the username form.
        "authenticationFlows": [
            flow("citizen browser", "Username + one-time code", [
                execution("auth-cookie", "ALTERNATIVE", 10),
                execution(None, "ALTERNATIVE", 20, flow_alias="citizen browser forms"),
            ]),
            flow("citizen browser forms", "username then OTP", [
                execution("auth-username-form", "REQUIRED", 10),
                execution("auth-otp-form", "REQUIRED", 20),
            ], top_level=False),
        ],
        "browserFlow": "citizen browser",
        "requiredActions": required_actions(default_totp=True),
    }


for rep in (staff_realm(), citizen_realm()):
    path = os.path.join(HERE, "realms", rep["realm"] + "-realm.json")
    with open(path, "w") as f:
        json.dump(rep, f, indent=2, ensure_ascii=False)
        f.write("\n")
    print("wrote", path)
